### ISSUE TITLE
Carved Animal and Bonfire Buttons do not register clicks on the whole button

### ISSUE THREAD

**Issue by Lexden12** [CPhuong24/UPJam2024#3]

**Comment by hoser21** [comment]
I'm seeing something like this. When I bought the first item, I  can but the carved animal, but the bonfire one doesn't work (the dialog option to purchase doesn't pop up). I have enough logs to purchase it.

**Comment by hoser21** [comment]
I think it's always the second and third shop item has trouble.

**Comment by Lexden12** [comment]
Pause menu buttons are consuming the clicks

**Comment by Lexden12** [comment]
Fixed by changing shop menu to a Canvas Layer.
